<?php // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

/*
$str="mohamed:qrt235234@#%!";
$aut= base64_encode($str);
echo $aut;
echo $result;
die();
*/

$base64_usrpwd = base64_encode('harm:hu1z3putm4n');
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'http://jira.foursites.nl/rest/api/2/user?username=mohamed');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json','Authorization: Basic '.$base64_usrpwd));
$curl_response = curl_exec($ch);

if ($curl_response === false) {
    $info = curl_getinfo($curl);
    curl_close($curl);
    die('error occured during curl exec. Additioanl info: ' . var_export($info));
}
echo $curl_response;
echo json_decode($curl_response);
/*if (isset($decoded->response->status) && $decoded->response->status == 'ERROR') {
    die('error occured: ' . $decoded->response->errormessage);
}
echo 'response ok!';*/
curl_close($ch);
die();


$base64_usrpwd = base64_encode('harm:hu1z3putm4n');

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'http://jira.foursites.nl/rest/api/2/issue/');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json',
  'Authorization: Basic '.$base64_usrpwd));
$arr['project'] = array( 'key' => 'SUPPORT');
$arr['summary'] = 'MO TEST Assignee copy 11:36';
$arr['description'] = 'MO TEST Assignee';
$arr['issuetype'] = array( 'name' => 'Bug');
$arr['reporter'] = array( 'name' => 'mohamed.hajjej@esprit.tn');
$arr['assignee'] = array( 'name' => 'mohamed');
$json_arr['fields'] = $arr;
$json_string = json_encode ($json_arr);
curl_setopt($ch, CURLOPT_POSTFIELDS,$json_string);
$result = curl_exec($ch);
curl_close($ch);

echo $result;
die();





/*********** basic authentification to jira server ***************/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/issue/SUPPORT-5434/comment");
/*curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/search?jql=assignee=mohamed");
curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/issue/SUPPORT-4956");*/
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

curl_setopt($ch, CURLOPT_USERPWD, "harm" . ":" . "hu1z3putm4n");

$headers = array();
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
echo $result;

//print json_encode($result);
if (curl_errno($ch)) {
  echo 'Error:' . curl_error($ch);
}

/*
curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/search?jql=assignee=mohamed&gt;updated>=2017-10-05");
curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/search?jql=assignee=mohamed");
curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/issue/SUPPORT-4956");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
$headers = array();
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$data = json_decode($result);
print_r($data);

*/



/******* check the current session **************/
curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/auth/latest/session");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
echo $result;
if (curl_errno($ch)) {
  echo 'Error:' . curl_error($ch);
}


/******* check the current session **************/

curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/wiki/jira/rest/api/2/user?username=mohamed.hajjej@foursites.nl");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

curl_setopt($ch, CURLOPT_USERPWD, "harm" . ":" . "hu1z3putm4n");

$result = curl_exec($ch);
echo $result;
if (curl_errno($ch)) {
  echo 'Error:' . curl_error($ch);
}
die();

/******* CREATE AN ISSUES **************/

curl_setopt($ch, CURLOPT_URL, "http://jira.foursites.nl/rest/api/2/issue/");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_USERPWD, "harm" . ":" . "hu1z3putm4n");

$headers = array();
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
  echo 'Error:' . curl_error($ch);
}
echo $result;
curl_close ($ch);


